[project]
name = "puzzgrid-button"
version = "0.1.0"
description = "Button to open the latest unattempted puzzgrid"
requires-python = ">=3.11"
dependencies = [
    "pillow>=12.0.0",
    "requests>=2.32.5",
    "typing-extensions>=4.15.0",
]
